# Generated by Django 3.2.4 on 2021-12-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brief',
            field=models.TextField(blank=True, null=True),
        ),
    ]
